site_name: DeskPi Products Wiki
site_url: https://wiki.deskpi.com

nav:
        - Home: index.md
        - DeskPi RackMate T1: rackmate.md
        - DeskPi MicroCar: microcar.md
        - DeskPi Lite NAS Case: deskpi_lite_nas_case.md
        - DeskPi Lite Expansion Kit: expansionkit.md
        - DeskPi Lite For Raspberry Pi 3B/3B+ : deskpi_lite_for_3b.md
        - DeskPi Mini PC: minipc.md
        - DeskPi PicoMate: picomate.md
        - DeskPi Super6C: super6c.md
        - DeskPi ITX Case Kit for Super6C: itxcase.md
        - DeskPi Lite: deskpilite.md
        - DeskPi Nano: deskpinano.md
        - DeskPi Pro: deskpipro.md
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list 
  - md_in_html
