site_name: DeskPi Products Wiki
site_url: https://wiki.deskpi.com

nav:
        - Home: index.md
        - DeskPi Lite Expansion Kit: expansionkit.md
        - DeskPi Mini PC: minipc.md
        - DeskPi PicoMate: picomate.md
        - DeskPi Super6C: super6c.md
        - DeskPi Lite: deskpilite.md
        - DeskPi Nano: deskpinano.md
        - DeskPi Pro: deskpipro.md
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list 

